### ISSUE TITLE
Press backspace in empty first point of a region to delete it

### ISSUE THREAD

**Issue by HoldingHands** [USHIN-Inc/ushin-ui-components#43]
If a region contains more than one point, and the cursor is placed in the first point and that point contains no text at all (or it contains only whitespace and the cursor is at the beginning of the point), then delete that first point and move the cursor to the following point (which replaces the first point).

**Comment by josephmturner** [comment]
fixed in [this commit](https://github.com/USHIN-Inc/ushin-ui-components/commit/20b1486d16a029296da286cab25e1101f83570f4)
