### ISSUE TITLE
Replace banner PNG with SVG

### ISSUE THREAD

**Issue by HoldingHands** [USHIN-Inc/ushin-ui-components#50]
Explore using SVG with preserveAspectRatio="none" instead of PNG as the banner background image.

**Comment by josephmturner** [comment]
How does one pass props to a background SVG? AFAICT, background SVGs cannot be inline. Is this correct?
If so, could the Banner SVG be a component whose width is dynamically set by the width of a different component which contains the text of the author's handle?
We want to be able to set the stroke color of the background SVG to the author's chosen color. Is this possible without passing props to an SVG component?

**Comment by josephmturner** [comment]
resolved in PR #85
